// ============================================
// PowerPoint Export Service
// Exports charts and dashboards to PPTX format
// Uses pptxgenjs for slide generation
// ============================================

import PptxGenJS from 'pptxgenjs';

export interface PptxExportOptions {
    filename?: string;
    title?: string;
    author?: string;
    /** Include a title slide at the beginning */
    includeTitleSlide?: boolean;
}

/**
 * Convert an HTML canvas element to a base64 PNG data string (without the data:image/png;base64, prefix)
 */
function canvasToBase64(canvas: HTMLCanvasElement): string {
    const dataURL = canvas.toDataURL('image/png', 1.0);
    // pptxgenjs expects base64 without the prefix
    return dataURL;
}

/**
 * Export a single chart to PowerPoint
 * @param element - Container element containing the ECharts canvas
 * @param options - Export options
 */
export async function exportChartToPPTX(
    element: HTMLElement,
    options: PptxExportOptions = {}
): Promise<void> {
    const {
        filename = 'chart.pptx',
        title = 'Chart',
        author = 'OpenViz',
        includeTitleSlide = false,
    } = options;

    const canvas = element.querySelector('canvas');
    if (!canvas) {
        throw new Error('No chart canvas found');
    }

    const pptx = new PptxGenJS();
    pptx.author = author;
    pptx.title = title;

    // Optional title slide
    if (includeTitleSlide) {
        const titleSlide = pptx.addSlide();
        titleSlide.background = { color: '0F172A' };
        titleSlide.addText(title, {
            x: 0.5,
            y: 2.0,
            w: 9,
            h: 1.5,
            fontSize: 32,
            fontFace: 'Arial',
            color: 'FAFAFA',
            align: 'center',
            bold: true,
        });
        titleSlide.addText('Generated by OpenViz', {
            x: 0.5,
            y: 3.5,
            w: 9,
            h: 0.5,
            fontSize: 12,
            fontFace: 'Arial',
            color: '94A3B8',
            align: 'center',
        });
    }

    // Chart slide
    const chartSlide = pptx.addSlide();
    chartSlide.background = { color: '1A1A2E' };

    // Add title
    chartSlide.addText(title, {
        x: 0.3,
        y: 0.2,
        w: 9.4,
        h: 0.5,
        fontSize: 18,
        fontFace: 'Arial',
        color: 'FAFAFA',
        bold: true,
    });

    // Add chart image
    const imageData = canvasToBase64(canvas);
    const aspectRatio = canvas.width / canvas.height;

    // Calculate dimensions to fit the slide with margins
    const maxWidth = 9.0; // inches
    const maxHeight = 5.8; // inches (leaving room for title)
    let imgWidth = maxWidth;
    let imgHeight = maxWidth / aspectRatio;

    if (imgHeight > maxHeight) {
        imgHeight = maxHeight;
        imgWidth = maxHeight * aspectRatio;
    }

    // Center horizontally
    const x = (10.0 - imgWidth) / 2;

    chartSlide.addImage({
        data: imageData,
        x,
        y: 0.9,
        w: imgWidth,
        h: imgHeight,
    });

    await pptx.writeFile({ fileName: filename });
    console.log('[Export] PPTX generated successfully:', filename);
}

/**
 * Export dashboard (multiple charts) to PowerPoint
 * Each chart gets its own slide
 * @param element - Dashboard container element with multiple canvases
 * @param title - Dashboard title
 * @param chartTitles - Optional array of chart titles matching canvas order
 * @param options - Export options
 */
export async function exportDashboardToPPTX(
    element: HTMLElement,
    title: string,
    chartTitles: string[] = [],
    options: PptxExportOptions = {}
): Promise<void> {
    const {
        filename = `${title.replace(/\s+/g, '_')}.pptx`,
        author = 'OpenViz',
    } = options;

    const canvases = element.querySelectorAll('canvas');
    if (canvases.length === 0) {
        throw new Error('No charts found in dashboard');
    }

    const pptx = new PptxGenJS();
    pptx.author = author;
    pptx.title = title;

    // Title slide
    const titleSlide = pptx.addSlide();
    titleSlide.background = { color: '0F172A' };
    titleSlide.addText(title, {
        x: 0.5,
        y: 1.8,
        w: 9,
        h: 1.5,
        fontSize: 36,
        fontFace: 'Arial',
        color: 'FAFAFA',
        align: 'center',
        bold: true,
    });
    titleSlide.addText(`${canvases.length} Charts`, {
        x: 0.5,
        y: 3.3,
        w: 9,
        h: 0.5,
        fontSize: 16,
        fontFace: 'Arial',
        color: '818CF8',
        align: 'center',
    });
    titleSlide.addText('Generated by OpenViz', {
        x: 0.5,
        y: 4.5,
        w: 9,
        h: 0.4,
        fontSize: 11,
        fontFace: 'Arial',
        color: '64748B',
        align: 'center',
    });

    // One slide per chart
    canvases.forEach((canvas, index) => {
        try {
            const slide = pptx.addSlide();
            slide.background = { color: '1A1A2E' };

            const chartTitle = chartTitles[index] || `Chart ${index + 1}`;

            // Add chart title
            slide.addText(chartTitle, {
                x: 0.3,
                y: 0.2,
                w: 9.4,
                h: 0.5,
                fontSize: 18,
                fontFace: 'Arial',
                color: 'FAFAFA',
                bold: true,
            });

            // Add chart image
            const imageData = canvasToBase64(canvas);
            const aspectRatio = canvas.width / canvas.height;

            const maxWidth = 9.0;
            const maxHeight = 5.8;
            let imgWidth = maxWidth;
            let imgHeight = maxWidth / aspectRatio;

            if (imgHeight > maxHeight) {
                imgHeight = maxHeight;
                imgWidth = maxHeight * aspectRatio;
            }

            const x = (10.0 - imgWidth) / 2;

            slide.addImage({
                data: imageData,
                x,
                y: 0.9,
                w: imgWidth,
                h: imgHeight,
            });

            // Slide number
            slide.addText(`${index + 1} / ${canvases.length}`, {
                x: 8.5,
                y: 7.0,
                w: 1.2,
                h: 0.3,
                fontSize: 9,
                fontFace: 'Arial',
                color: '64748B',
                align: 'right',
            });
        } catch (err) {
            console.warn(`[Export] Failed to export chart ${index + 1} to PPTX:`, err);
        }
    });

    await pptx.writeFile({ fileName: filename });
    console.log('[Export] Dashboard PPTX generated successfully:', filename);
}
